config/routes.rb
LanguageMining::Application.routes.draw do

  root 'homes#index'
  resources :poems

end

app/models/author.rb
class Author < ActiveRecord::Base
  default_scope { order('name') }
  has_many :poems
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/daily_poem.rb
class DailyPoem < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_local_language

  def set_local_language
    I18n.locale = 'kn'
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @poem = Poem.order("RAND()").first
  end

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

  def index
    @author = Author.find_by_id(params[:author])
    @poems = if @author
               @author.poems.paginate(:page => params[:page], :per_page => 35)
             else
               Poem.paginate(:page => params[:page], :per_page => 35)
             end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/homes/index.html.erb
<div class="vachana_sangraha_heading">
  <h1> <%= t :menu_brand_name %> </h1>
</div>

<div class="sangraha_desc">

  <div class="rand-vachana">
    <h3> <%= t :today_poem %> </h3>
    <p>
      <%= raw @poem.poem_text.gsub(/\n/, '<br />') %>
    </p>
    <span class="vachanakaara-name" style="margin-left:20%;"> --- <%= @poem.author.name %> </span>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= t :brand_title %> </title>
  <%= stylesheet_link_tag    "application", media: "all"  %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

<div class="navbar">
  <div class="navbar-inner">
    <a href="<%= root_path %> " class="brand">
      <%= t :menu_brand_name %> <sub> alpha </sub>
    </a>
    <ul class="nav">
      <li> <%= link_to t(:menu_bar_author), "#" %> </li>
      <li> <%= link_to t(:menu_bar_poem), poems_path %> </li>
      <li> <%= link_to t(:menu_bar_glossary), "#" %> </li>
      <li> <%= link_to t(:menu_bar_contact_us), "#" %> </li>
      <li> <%= link_to t(:menu_bar_about_us), "#" %> </li>
    </ul>

    <ul class="nav" style="float: right;">
      <li>
        <%= link_to("https://www.facebook.com/daasasanchaya", target: "_blank", class: "social-nav-right ") do %>
            <i class="fa fa-facebook fa-2x"></i>
        <% end %>
      </li>
      <li>
        <%= link_to("http://twitter.com/daasasanchaya" , target: "_blank",class: "social-nav-right ") do %>
            <i class="fa fa-twitter fa-2x"></i>
        <% end %>
      </li>
    </ul>

  </div>
</div>

<div class="container">
  <%= yield %>
</div>

<div class="footer">
  <div class="navbar-inner">
    <div class="copy-right">
      © 2014  <a href="http://kannada.sanchaya.net" target="_blank"> ಕನ್ನಡ ಸಂಚಯ  </a>| ಸಾಹಿತ್ಯ ಸಂಶೋಧನೆ ಹಾಗೂ ಅಧ್ಯಯನ ವೇದಿಕೆ
    </div>
  </div>
</div>
</body>
</html>

app/views/poems/index.html.erb
<div class="search_box">
  <%= form_tag poems_path, name: "search_poem", id: "main_search", method: :get do %>
      <%= select_tag "author", options_from_collection_for_select(Author.all, "id", "name", params[:author]), prompt: "#{t :all}" %>
      <%= submit_tag "#{t :search}", :disable_with => "#{t :please_wait}...", :class => 'btn btn-primary' %>
  <% end %>
</div>


<div class="results_list_div ">
  <% @poems.each do |poem| %>

      <a href="#myModal_<%= poem.id %>" role="button" data-toggle="modal" class="modal-pop-a">
        <div class="box effect5">
          <div class="vachana-concord-box">
            <div class="vachana-show-box">
              <span>  <%= poem.poem_text %> </span>
            </div>
            --------------
            <div class="vachanakaara-name">
       <span  >
         <%= "#{poem.author.name}" %>
       </span>
            </div>
          </div>
        </div>
      </a>

      <div id="myModal_<%= poem.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">
      <span class="vachanakaara-name">
        <%= "#{poem.author.name}" %>
      </span>
          </h3>
        </div>
        <div class="modal-body vachana-pop">
          <p id='fe_text_<%= poem.id %>'> <%= raw poem.poem_text.gsub(/\n/, '<br />') %>

          </p>
        </div>
        <div class="modal-footer">
          <div class='demo-area'>

          </div>
        </div>
      </div>
  <% end %>
  <div class="pagination apple_pagination">
    <%= will_paginate @poems %>
  </div>
</div>